import { Router } from 'express';

import routerPopulate from '../../modules/_populate/routes';
import routerApportion from '../../modules/apportion/routes';
import routerCompany from '../../modules/company/routes';
import routerCompanyContact from '../../modules/companyContact/routes';
import routerContactType from '../../modules/contactType/routes';
import routerCostCenter from '../../modules/costCenter/routes';
import routerDeviceType from '../../modules/deviceType/routes';
import routerGroup from '../../modules/group/routes';
import routerLocation from '../../modules/location/routes';
import routerMenu from '../../modules/menu/routes';
import routerProfile from '../../modules/profile/routes';
import routerSector from '../../modules/sector/routes';
import routerStatus from '../../modules/status/routes';
import routerSync from '../../modules/sync/routes';
import routerUser from '../../modules/user/routes';
import routerUserCostCenter from '../../modules/user_costcenter/routes';
import routerUserSector from '../../modules/user_Sector/routes';

const routes = Router();

routes.use('/populate', routerPopulate);
routes.use('/location', routerLocation);
routes.use('/sync', routerSync);
routes.use('/status', routerStatus);
routes.use('/profile', routerProfile);
routes.use('/costCenter', routerCostCenter);
routes.use('/userCostCenter', routerUserCostCenter);
routes.use('/sector', routerSector);
routes.use('/userSector', routerUserSector);
routes.use('/user', routerUser);
routes.use('/apportion', routerApportion);
routes.use('/group', routerGroup);
routes.use('/menu', routerMenu);
routes.use('/contactType', routerContactType);
routes.use('/company', routerCompany);
routes.use('/company', routerCompanyContact);
routes.use('/deviceType', routerDeviceType);
export default routes;
